"""empty message

Revision ID: 26ca599d0564
Revises: 
Create Date: 2018-05-05 13:44:17.992687

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '26ca599d0564'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('album_user',
    sa.Column('album_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('album_id'),
    sa.UniqueConstraint('timestamp')
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('mean_encoding', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('kid_id', sa.Integer(), nullable=True),
    sa.Column('is_labeled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ruby_id', sa.Integer(), nullable=True),
    sa.Column('image_hash', sa.String(length=512), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('added_on', sa.DateTime(), nullable=True),
    sa.Column('captions', sa.String(length=512), nullable=True),
    sa.Column('group_id', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('image_hash')
    )
    op.create_table('face',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('photo', sa.Integer(), nullable=True),
    sa.Column('encoding', postgresql.ARRAY(sa.Float()), nullable=True),
    sa.Column('person', sa.Integer(), nullable=True),
    sa.Column('person_is_labeled', sa.Boolean(), nullable=True),
    sa.Column('image_path', sa.String(length=64), nullable=True),
    sa.Column('location_top', sa.Integer(), nullable=True),
    sa.Column('location_bottom', sa.Integer(), nullable=True),
    sa.Column('location_left', sa.Integer(), nullable=True),
    sa.Column('location_right', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person'], ['person.id'], ),
    sa.ForeignKeyConstraint(['photo'], ['photo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('face')
    op.drop_table('photo')
    op.drop_table('person')
    op.drop_table('album_user')
    # ### end Alembic commands ###
