"""empty message

Revision ID: b762d3c5ba97
Revises: 26ca599d0564
Create Date: 2018-05-07 13:30:25.259666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b762d3c5ba97'
down_revision = '26ca599d0564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('default_face', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'person', 'face', ['default_face'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'person', type_='foreignkey')
    op.drop_column('person', 'default_face')
    # ### end Alembic commands ###
