"""empty message

Revision ID: c566cc031f6f
Revises: 1c5a6ee213cf
Create Date: 2018-05-10 09:09:32.356965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c566cc031f6f'
down_revision = '1c5a6ee213cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face', sa.Column('face_is_labeled', sa.Boolean(), nullable=True))
    op.drop_column('face', 'person_is_labeled')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('face', sa.Column('person_is_labeled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('face', 'face_is_labeled')
    # ### end Alembic commands ###
