"""empty message

Revision ID: c9f25a08ac6d
Revises: c566cc031f6f
Create Date: 2018-05-15 13:25:34.463753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9f25a08ac6d'
down_revision = 'c566cc031f6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('is_kid', sa.Boolean(), nullable=True))
    op.drop_column('person', 'is_labeled')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('is_labeled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('person', 'is_kid')
    # ### end Alembic commands ###
